/* 
/tsinswreng-elucidate/SKILL.typ是唯一內容源。
Langs/zh-Hant
Langs/zh-Hans 裏的內容都由此自動生成
 */
#r "nuget: Tsinswreng.CsSh, 0.3.0-alpha"
#r "nuget: OpenCC, 0.1.0"
#nullable enable
using CT = System.Threading.CancellationToken;
using Tsinswreng.CsSh;
using static Tsinswreng.CsSh.ShGlobal;

using OpenCC;

CT Ct = default;

Pth Dir = CsxDir();
Pth SrcDir = Dir / "tsinswreng-elucidate";

// README.md 不由本腳本生成，見 _Mvn/skill-elucidate/GenReadme.csx。
// 生成物開頭標明是自動生成的，防止有人直接手改生成物。
var Note = "本文件由 Build.csx 自動生成，請勿手改；內容源是 tsinswreng-elucidate/SKILL.typ。";

// Langs/zh-Hant 直接複製源；Langs/zh-Hans 是源過 OpenCC 繁轉簡。
var ToHans = OpenCC.OpenCC.Converter("tw", "cn");
foreach(var Lang in new[]{"zh-Hant", "zh-Hans"}){
	Pth LangDir = Dir / "Langs" / Lang / "tsinswreng-elucidate";
	foreach(Pth F in Glob(SrcDir / "*.typ")){
		Content C = await Read(F, Ct);
		var Txt = await C.Text(Ct);
		var Out = "// " + Note + (Txt.Contains("\r\n") ? "\r\n" : "\n") + Txt;
		await Write(LangDir / BaseName(F), Lang == "zh-Hans" ? ToHans(Out) : Out, Ct);
	}
}

// 每個語言目錄（zh-Hant、zh-Hans、手寫的 en 等）都由自己的 SKILL.typ 生成 SKILL.md。
foreach(Pth LangDir in LsDir(Dir / "Langs")){
	Pth SkillDir = LangDir / "tsinswreng-elucidate";
	string Lang = BaseName(LangDir);
	var MdNote = Lang switch {
		"en" => "<!-- Auto-generated by Build.csx. Edit Langs/en/tsinswreng-elucidate/SKILL.typ, not this file. -->",
		"zh-Hans" => "<!-- " + ToHans(Note) + " -->",
		_ => "<!-- " + Note + " -->",
	};
	await Write(SkillDir / "SKILL.md", MdWithNote(await TypstToMd(await Read(SkillDir / "SKILL.typ", Ct), SkillDir, Ct), MdNote), Ct);
}

// typst 源 -> Markdown。兩步都走 stdin/stdout 管道，不落任何臨時文件。
// Root 供 typst 解析相對的 #include/#import；stdin 模式下相對路徑按 Root 解析，自包含的文檔可傳 null。
static async Task<string> TypstToMd(Content Src, Pth? Root, CT Ct){
	var Html = await Cmd("typst", new[]{"compile","-","-","--format","html","--features","html"},
		new CommandOptions(Stdin: Src, Cwd: Root)).Text(Ct);
	if(!Html.Exit.IsSuccess){ throw new Exception($"typst 失敗({Html.Exit.ExitCode}): {Html.Stderr}"); }
	var Md = await Cmd("pandoc", new[]{"-f","html","-t","gfm","--wrap=none"},
		new CommandOptions(Stdin: Html.Stdout)).Text(Ct);
	if(!Md.Exit.IsSuccess){ throw new Exception($"pandoc 失敗({Md.Exit.ExitCode}): {Md.Stderr}"); }
	return Md.Stdout;
}

// 把註釋插在 md 的 frontmatter 之後。放檔首會讓 frontmatter 不再是檔首，解析會失敗。
static string MdWithNote(string Md, string Note){
	var L = Md.Replace("\r\n", "\n").Split('\n');
	var First = Array.IndexOf(L, "---");
	var End = First < 0 ? -1 : Array.IndexOf(L, "---", First + 1);
	var Out = End < 0
		? Note + "\n\n" + string.Join("\n", L)
		: string.Join("\n", L[..(End + 1)]) + "\n\n" + Note + "\n" + string.Join("\n", L[(End + 1)..]);
	return Out.Replace("\n", "\r\n");
}